---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubevirt.io: ""
  name: hyperconverged-cluster-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hyperconverged-cluster-operator
subjects:
- kind: ServiceAccount
  name: hyperconverged-cluster-operator
  namespace: kubevirt-hyperconverged
